### ISSUE TITLE
Anydesk 内网使用

### ISSUE THREAD

**Issue by lichuyi0720** [RuoJi6/Deskbypass#2]
内网主机 B  172.16.110.6
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/afd3f3c0-2d99-4c6c-bec0-dfd5e6e7896f)
多网卡主机A  172.16.110.5  
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/7e4499df-fe8d-4cf8-89a1-30ad128d2be5)
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/ca373513-7582-4a08-8789-fd009aee4081)
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/6279b344-589a-446e-b835-15b46ce943cb)
B连接A 
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/f5ed596b-f8ec-4cea-848d-7efffffa7090)
A连接B
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/83a61c63-ef13-49d8-9cdf-c01554000636)
![图片](https://github.com/RuoJi6/Deskbypass/assets/121230186/aef4c103-20c8-471b-a696-cc4110fea87b)
师傅描述的那种报错，刚刚遇到了，双主机重启anydesk 即可

**Comment by RuoJi6** [comment]
但是实战环境下，重启主机会导致一些问题
