### ISSUE TITLE
建议增加RayLink

### ISSUE THREAD

**Issue by bianyuan456** [RuoJi6/Deskbypass#3]
这款远程软件因为可以免费使用不限制画质、可以控制投屏手柄、支持144HZ刷新率等在别的软件上面收费的功能，所以用的人比较多，希望增加这个远程软件的支持！
https://www.raylink.live/

**Comment by RuoJi6** [comment]
好的

**Comment by RuoJi6** [comment]
刚刚实验了一下，发现
![image](https://github.com/RuoJi6/Deskbypass/assets/79234113/5f552728-4a3c-4965-b638-5d6458e15de8)
是绑定mac地址的而且
配置文件是在：C:\ProgramData\RayLinkLite这个文件夹[需要管理员权限]
而且还会触发uac
